#!/bin/bash

command="ssh -o PreferredAuthentications=publickey \
	-o PasswordAuthentication=no \
	-o PubkeyAuthentication=yes \
	-o StrictHostKeyChecking=no \
	-o UserKnownHostsFile=/dev/null \
	$@"

if [[ "X$EUID" = "X$(id --user ansible)" ]] ; then
	eval $command
elif [[ "X$EUID" = "X$(id --user root)" ]] ; then
	su - ansible -c "$command"
else
	echo "This command only supports being executed as \"ansible\" or \"root\"!" 1>&2
	exit 1
fi

