#!/bin/bash

set -e -o pipefail

if [[ -z "${2}" ]] ; then
	echo "usage: ${0} <hostname> [<args> ...]" >&2
	echo "ex: ${0} myhost -m ping -vv --extra-vars 'var1=val1'" >&2
	echo "    ${0} myhost --ask-become --become -a 'ssh-add -l'" >&2
	exit 1
fi

host=$(echo "${1}" | tr "," "\n")
shift

inventory="$(mktemp --suffix=.yml)"
function cleanup {
	[[ -z "${ANSIBLE_DEBUG}" ]] && rm --force -- "${inventory}"
}
trap cleanup EXIT SIGINT

cat <<- EOF > "${inventory}"
	[section]
	${host}

	[section:vars]
	ansible_python_interpreter=/usr/bin/python3
EOF

export ANSIBLE_RETRY_FILES_ENABLED=false
ansible \
	--inventory-file="${inventory}" \
	section \
	"${@}"

