#!/bin/bash

set -e -o pipefail

if [[ -z "${2}" ]] ; then
	echo "usage: ${0} <hostname> <role> [<args> ...]" >&2
	echo "ex: ${0} myhost myrole -vv --extra-vars 'var1=val1'" >&2
	exit 1
fi

host=$(echo "${1}" | tr "," "\n")
role=$(echo "${2}" | sed --expression=$'s/,/\\n	  - /g')
shift 2

# Note: Doesn't gather facts
#ansible $hosts -m include_role -a "name=$role"

inventory="$(mktemp --suffix=.yml)"
function cleanup {
	[[ -z "${ANSIBLE_DEBUG}" ]] && rm --force -- "${inventory}"
}
trap cleanup EXIT SIGINT

cat <<- EOF > "${inventory}"
	[section]
	${host}

	[section:vars]
	ansible_python_interpreter=/usr/bin/python3
EOF

export ANSIBLE_RETRY_FILES_ENABLED=false
ansible-playbook \
	--ask-become \
	--inventory-file="${inventory}" \
	"${@}" \
	/dev/stdin <<-EOF
	---
	- hosts: section
	  roles:
	  - role: ${role}
EOF

